"""empty message

Revision ID: 1cf660919b0e
Revises: 596099df4dee
Create Date: 2022-11-19 12:17:55.918841

"""
import sqlalchemy as sa
from alembic import op
from app.db.custom_types import utcnow
from sqlalchemy.dialects.oracle import TIMESTAMP

# revision identifiers, used by Alembic.
revision = '1cf660919b0e'
down_revision = '596099df4dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LOT',
        sa.Column(
                "id",
                sa.Integer,
                sa.Identity(),
                primary_key=True,
            ),
        sa.Column('name', sa.String(50), nullable=True),
        sa.Column('fruit_id', sa.Integer(), nullable=True),
        sa.Column('timestamp_arrival', TIMESTAMP(), server_default=utcnow(), nullable=False),
        sa.Column('weight', sa.Float(), server_default="1", nullable=False),
        sa.Column('volume', sa.Float(), server_default="1", nullable=False),
        sa.Column('ripens_level', sa.Float(), server_default="0.5", nullable=False),
        sa.Column('price', sa.Float(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(['fruit_id'], ['FRUIT.id'], ),
    )
    op.create_index(op.f('ix_LOT_name'), 'LOT', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LOT_name'), table_name='LOT')
    op.drop_index(op.f('ix_LOT_id'), table_name='LOT')
    op.drop_table('LOT')
    # ### end Alembic commands ###
