"""empty message

Revision ID: 240f25edcc2d
Revises: 1cf660919b0e
Create Date: 2022-11-19 15:45:02.455527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240f25edcc2d'
down_revision = '1cf660919b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ALLERGY',
        sa.Column(
            "id",
            sa.Integer,
            sa.Identity(),
            primary_key=True,
        ),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('symptoms', sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ALLERGY_name'), 'ALLERGY', ['name'], unique=False)
    
    op.create_table('ALLERGIES_FRUITS',
        sa.Column('allergy_id', sa.Integer(), nullable=False),
        sa.Column('fruit_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['allergy_id'], ['ALLERGY.id'], ),
        sa.ForeignKeyConstraint(['fruit_id'], ['FRUIT.id'], ),
        sa.PrimaryKeyConstraint('allergy_id', 'fruit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ALLERGIES_FRUITS')
    op.drop_index(op.f('ix_ALLERGY_name'), table_name='ALLERGY')
    op.drop_table('ALLERGY')
    # ### end Alembic commands ###
