"""empty message

Revision ID: 433d303034ce
Revises: 240f25edcc2d
Create Date: 2022-11-19 19:12:05.098233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433d303034ce'
down_revision = '240f25edcc2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RECIPE',
        sa.Column(
            "id",
            sa.Integer,
            sa.Identity(),
            primary_key=True,
        ),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RECIPE_name'), 'RECIPE', ['name'], unique=False)
    
    op.create_table('RECIPES_FRUITS',
        sa.Column('recipe_id', sa.Integer(), nullable=False),
        sa.Column('fruit_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['recipe_id'], ['RECIPE.id'], ),
        sa.ForeignKeyConstraint(['fruit_id'], ['FRUIT.id'], ),
        sa.PrimaryKeyConstraint('recipe_id', 'fruit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RECIPES_FRUITS')
    op.drop_index(op.f('ix_RECIPE_name'), table_name='RECIPE')
    op.drop_table('RECIPE')
    # ### end Alembic commands ###
