"""empty message

Revision ID: 596099df4dee
Revises: 
Create Date: 2022-11-18 18:57:37.599048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596099df4dee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FRUIT',
        sa.Column(
            "id",
            sa.Integer,
            sa.Identity(),
            primary_key=True,
        ),
        sa.Column('name', sa.String(50), nullable=True),
        sa.Column('peel_type', sa.Enum('EDIBLE', 'NOT EDIBLE', name='peeltypeenum'), server_default='EDIBLE', nullable=False),
    )
    op.create_index(op.f('ix_FRUIT_name'), 'FRUIT', ['name'], unique=False)
    
    op.create_table('USER',
        sa.Column(
            "id",
            sa.Integer,
            sa.Identity(),
            primary_key=True,
        ),        
        sa.Column('full_name', sa.String(100), nullable=True),
        sa.Column('email', sa.String(100), nullable=False),
        sa.Column('hashed_password', sa.String(200), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_superuser', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_USER_email'), 'USER', ['email'], unique=True)
    op.create_index(op.f('ix_USER_full_name'), 'USER', ['full_name'], unique=False)
    
    op.create_table('ITEM',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(100), nullable=True),
    sa.Column('description', sa.String(100), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ITEM_description'), 'ITEM', ['description'], unique=False)
    op.create_index(op.f('ix_ITEM_title'), 'ITEM', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ITEM_title'), table_name='ITEM')
    op.drop_index(op.f('ix_ITEM_id'), table_name='ITEM')
    op.drop_index(op.f('ix_ITEM_description'), table_name='ITEM')
    op.drop_table('ITEM')
    op.drop_index(op.f('ix_USER_id'), table_name='USER')
    op.drop_index(op.f('ix_USER_full_name'), table_name='USER')
    op.drop_index(op.f('ix_USER_email'), table_name='USER')
    op.drop_table('USER')
    op.drop_index(op.f('ix_FRUIT_name'), table_name='FRUIT')
    op.drop_index(op.f('ix_FRUIT_id'), table_name='FRUIT')
    op.drop_table('FRUIT')
    # ### end Alembic commands ###
