"""First revision

Revision ID: d4867f3a4c0a
Revises:
Create Date: 2019-04-17 13:53:32.978401

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "d4867f3a4c0a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "USER",
        sa.Column(
            "id",
            sa.Integer,
            sa.Identity(),
            primary_key=True,
        ),
        sa.Column("full_name", sa.String(100), nullable=True),
        sa.Column("email", sa.String(100), nullable=True),
        sa.Column("hashed_password", sa.String(500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
    )
    op.create_index(op.f("ix_user_email"), "USER", ["email"], unique=True)
    op.create_index(op.f("ix_user_full_name"), "USER", ["full_name"], unique=False)
    op.create_table(
        "ITEM",
        sa.Column(
            "id",
            sa.Integer,
            sa.Identity(),
            primary_key=True,
        ),        
        sa.Column("title", sa.String(100), nullable=True),
        sa.Column("description", sa.String(500), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["USER.id"],),
    )
    op.create_index(op.f("ix_item_description"), "ITEM", ["description"], unique=False)
    op.create_index(op.f("ix_item_title"), "ITEM", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.execute("drop schema APP")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_title"), table_name="ITEM")
    op.drop_index(op.f("ix_item_id"), table_name="ITEM")
    op.drop_index(op.f("ix_item_description"), table_name="ITEM")
    op.drop_table("ITEM")
    op.drop_index(op.f("ix_user_id"), table_name="USER")
    op.drop_index(op.f("ix_user_full_name"), table_name="USER")
    op.drop_index(op.f("ix_user_email"), table_name="USER")
    op.drop_table("USER")
    # ### end Alembic commands ###
