"""empty message

Revision ID: e6cae4906f3e
Revises: 433d303034ce
Create Date: 2022-11-22 21:27:09.442404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cae4906f3e'
down_revision = '433d303034ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SENSOR',
        sa.Column(
                    "id",
                    sa.Integer,
                    sa.Identity(),
                    primary_key=True,
                ),    sa.Column('name', sa.String(), nullable=True),
        sa.Column('name', sa.String(100)),
        sa.Column('fruit_size', sa.Enum('LITTLE', 'MEDIUM', 'BIG', name='fruitsizeenum'), server_default='MEDIUM', nullable=False),
        sa.Column('medium_energy_consumption', sa.Float(), server_default='1', nullable=True),
        sa.Column('cost', sa.Float(), server_default='50', nullable=True),
        sa.Column('brand', sa.String(length=100), nullable=True),
    )
    op.create_index(op.f('ix_SENSOR_name'), 'SENSOR', ['name'], unique=False)
    op.create_table('SENSOR_FRUIT_ANALYSIS',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.Column('sensor_id', sa.Integer(), nullable=False),
        sa.Column('lot_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['sensor_id'], ['SENSOR.id']),
        sa.ForeignKeyConstraint(['lot_id'], ['LOT.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sensor_id', 'lot_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SENSOR_FRUIT_ANALYSIS')
    op.drop_index(op.f('ix_SENSOR_name'), table_name='SENSOR')
    op.drop_table('SENSOR')
    # ### end Alembic commands ###
